[package]
name = "lapce-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lapce-rpc.workspace = true
lapce-proxy.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
tokio = { version = "1.21", features = ["full"] }
futures = "0.3.26"
floem = { path = "../../workspaces/floem" }
